services:
  - type: web
    name: bellls
    env: static
    buildCommand: npm install && npm run build:libs
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
